// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: bileteprotobufs.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ubb.Scs.Mpp.Network {

  /// <summary>Holder for reflection information generated from bileteprotobufs.proto</summary>
  public static partial class BileteprotobufsReflection {

    #region Descriptor
    /// <summary>File descriptor for bileteprotobufs.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BileteprotobufsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChViaWxldGVwcm90b2J1ZnMucHJvdG8SE3ViYi5zY3MubXBwLk5ldHdvcmsi",
            "RwoHQW5nYWphdBIKCgJpZBgBIAEoAxIQCgh1c2VybmFtZRgCIAEoCRIQCghw",
            "YXNzd29yZBgDIAEoCRIMCgRtYWlsGAQgASgJInIKCVNwZWN0YWNvbBIKCgJp",
            "ZBgBIAEoAxIOCgZhcnRpc3QYAiABKAkSDAoEZGF0ZRgDIAEoCRIQCghsb2Nh",
            "dGlvbhgEIAEoCRIWCg5hdmFpbGFibGVTZWF0cxgFIAEoBRIRCglzb2xkU2Vh",
            "dHMYBiABKAUiagoFQmlsZXQSCgoCaWQYASABKAMSDQoFYnV5ZXIYAiABKAkS",
            "EwoLc2VhdHNOdW1iZXIYAyABKAUSMQoJc3BlY3RhY29sGAQgASgLMh4udWJi",
            "LnNjcy5tcHAuTmV0d29yay5TcGVjdGFjb2wi7QEKB1JlcXVlc3QSLwoEdHlw",
            "ZRgBIAEoDjIhLnViYi5zY3MubXBwLk5ldHdvcmsuUmVxdWVzdC5UeXBlEi0K",
            "B2FuZ2FqYXQYAiABKAsyHC51YmIuc2NzLm1wcC5OZXR3b3JrLkFuZ2FqYXQS",
            "KQoFYmlsZXQYAyABKAsyGi51YmIuc2NzLm1wcC5OZXR3b3JrLkJpbGV0EgwK",
            "BERhdGEYBCABKAkiSQoEVHlwZRINCglCdXlUaWNrZXQQABIJCgVMb2dpbhAB",
            "EgoKBkxvZ291dBACEgwKCEdldFNob3dzEAMSDQoJR2V0RlNob3dzEAQiywIK",
            "DlRpY2tldFJlc3BvbnNlEjYKBHR5cGUYASABKA4yKC51YmIuc2NzLm1wcC5O",
            "ZXR3b3JrLlRpY2tldFJlc3BvbnNlLlR5cGUSDQoFZXJyb3IYAiABKAkSKQoF",
            "YmlsZXQYAyABKAsyGi51YmIuc2NzLm1wcC5OZXR3b3JrLkJpbGV0Ei0KB2Fu",
            "Z2FqYXQYBSABKAsyHC51YmIuc2NzLm1wcC5OZXR3b3JrLkFuZ2FqYXQSLQoF",
            "c2hvd3MYBCADKAsyHi51YmIuc2NzLm1wcC5OZXR3b3JrLlNwZWN0YWNvbBIx",
            "CglzcGVjdGFjb2wYBiABKAsyHi51YmIuc2NzLm1wcC5OZXR3b3JrLlNwZWN0",
            "YWNvbCI2CgRUeXBlEgYKAk9rEAASDQoJTmV3VGlja2V0EAESCQoFRXJyb3IQ",
            "AhIMCghTaG93TGlzdBADQi8KHHViYi5zY3MubXBwLk5ldHdvcmsucHJvdG9i",
            "dWZCD0JpbGV0ZVByb3RvYnVmc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ubb.Scs.Mpp.Network.Angajat), global::Ubb.Scs.Mpp.Network.Angajat.Parser, new[]{ "Id", "Username", "Password", "Mail" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ubb.Scs.Mpp.Network.Spectacol), global::Ubb.Scs.Mpp.Network.Spectacol.Parser, new[]{ "Id", "Artist", "Date", "Location", "AvailableSeats", "SoldSeats" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ubb.Scs.Mpp.Network.Bilet), global::Ubb.Scs.Mpp.Network.Bilet.Parser, new[]{ "Id", "Buyer", "SeatsNumber", "Spectacol" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ubb.Scs.Mpp.Network.Request), global::Ubb.Scs.Mpp.Network.Request.Parser, new[]{ "Type", "Angajat", "Bilet", "Data" }, null, new[]{ typeof(global::Ubb.Scs.Mpp.Network.Request.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ubb.Scs.Mpp.Network.TicketResponse), global::Ubb.Scs.Mpp.Network.TicketResponse.Parser, new[]{ "Type", "Error", "Bilet", "Angajat", "Shows", "Spectacol" }, null, new[]{ typeof(global::Ubb.Scs.Mpp.Network.TicketResponse.Types.Type) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Angajat : pb::IMessage<Angajat>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Angajat> _parser = new pb::MessageParser<Angajat>(() => new Angajat());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Angajat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ubb.Scs.Mpp.Network.BileteprotobufsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Angajat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Angajat(Angajat other) : this() {
      id_ = other.id_;
      username_ = other.username_;
      password_ = other.password_;
      mail_ = other.mail_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Angajat Clone() {
      return new Angajat(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 2;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 3;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mail" field.</summary>
    public const int MailFieldNumber = 4;
    private string mail_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Mail {
      get { return mail_; }
      set {
        mail_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Angajat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Angajat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Username != other.Username) return false;
      if (Password != other.Password) return false;
      if (Mail != other.Mail) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (Mail.Length != 0) hash ^= Mail.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Password);
      }
      if (Mail.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Mail);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Password);
      }
      if (Mail.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Mail);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (Mail.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mail);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Angajat other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      if (other.Mail.Length != 0) {
        Mail = other.Mail;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 26: {
            Password = input.ReadString();
            break;
          }
          case 34: {
            Mail = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 26: {
            Password = input.ReadString();
            break;
          }
          case 34: {
            Mail = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Spectacol : pb::IMessage<Spectacol>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Spectacol> _parser = new pb::MessageParser<Spectacol>(() => new Spectacol());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Spectacol> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ubb.Scs.Mpp.Network.BileteprotobufsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Spectacol() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Spectacol(Spectacol other) : this() {
      id_ = other.id_;
      artist_ = other.artist_;
      date_ = other.date_;
      location_ = other.location_;
      availableSeats_ = other.availableSeats_;
      soldSeats_ = other.soldSeats_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Spectacol Clone() {
      return new Spectacol(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "artist" field.</summary>
    public const int ArtistFieldNumber = 2;
    private string artist_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Artist {
      get { return artist_; }
      set {
        artist_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "date" field.</summary>
    public const int DateFieldNumber = 3;
    private string date_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Date {
      get { return date_; }
      set {
        date_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "location" field.</summary>
    public const int LocationFieldNumber = 4;
    private string location_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Location {
      get { return location_; }
      set {
        location_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "availableSeats" field.</summary>
    public const int AvailableSeatsFieldNumber = 5;
    private int availableSeats_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AvailableSeats {
      get { return availableSeats_; }
      set {
        availableSeats_ = value;
      }
    }

    /// <summary>Field number for the "soldSeats" field.</summary>
    public const int SoldSeatsFieldNumber = 6;
    private int soldSeats_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SoldSeats {
      get { return soldSeats_; }
      set {
        soldSeats_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Spectacol);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Spectacol other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Artist != other.Artist) return false;
      if (Date != other.Date) return false;
      if (Location != other.Location) return false;
      if (AvailableSeats != other.AvailableSeats) return false;
      if (SoldSeats != other.SoldSeats) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Artist.Length != 0) hash ^= Artist.GetHashCode();
      if (Date.Length != 0) hash ^= Date.GetHashCode();
      if (Location.Length != 0) hash ^= Location.GetHashCode();
      if (AvailableSeats != 0) hash ^= AvailableSeats.GetHashCode();
      if (SoldSeats != 0) hash ^= SoldSeats.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Artist.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Artist);
      }
      if (Date.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Date);
      }
      if (Location.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Location);
      }
      if (AvailableSeats != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(AvailableSeats);
      }
      if (SoldSeats != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(SoldSeats);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Artist.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Artist);
      }
      if (Date.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Date);
      }
      if (Location.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Location);
      }
      if (AvailableSeats != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(AvailableSeats);
      }
      if (SoldSeats != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(SoldSeats);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (Artist.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Artist);
      }
      if (Date.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Date);
      }
      if (Location.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Location);
      }
      if (AvailableSeats != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AvailableSeats);
      }
      if (SoldSeats != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SoldSeats);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Spectacol other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Artist.Length != 0) {
        Artist = other.Artist;
      }
      if (other.Date.Length != 0) {
        Date = other.Date;
      }
      if (other.Location.Length != 0) {
        Location = other.Location;
      }
      if (other.AvailableSeats != 0) {
        AvailableSeats = other.AvailableSeats;
      }
      if (other.SoldSeats != 0) {
        SoldSeats = other.SoldSeats;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Artist = input.ReadString();
            break;
          }
          case 26: {
            Date = input.ReadString();
            break;
          }
          case 34: {
            Location = input.ReadString();
            break;
          }
          case 40: {
            AvailableSeats = input.ReadInt32();
            break;
          }
          case 48: {
            SoldSeats = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Artist = input.ReadString();
            break;
          }
          case 26: {
            Date = input.ReadString();
            break;
          }
          case 34: {
            Location = input.ReadString();
            break;
          }
          case 40: {
            AvailableSeats = input.ReadInt32();
            break;
          }
          case 48: {
            SoldSeats = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Bilet : pb::IMessage<Bilet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Bilet> _parser = new pb::MessageParser<Bilet>(() => new Bilet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Bilet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ubb.Scs.Mpp.Network.BileteprotobufsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Bilet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Bilet(Bilet other) : this() {
      id_ = other.id_;
      buyer_ = other.buyer_;
      seatsNumber_ = other.seatsNumber_;
      spectacol_ = other.spectacol_ != null ? other.spectacol_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Bilet Clone() {
      return new Bilet(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "buyer" field.</summary>
    public const int BuyerFieldNumber = 2;
    private string buyer_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Buyer {
      get { return buyer_; }
      set {
        buyer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "seatsNumber" field.</summary>
    public const int SeatsNumberFieldNumber = 3;
    private int seatsNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SeatsNumber {
      get { return seatsNumber_; }
      set {
        seatsNumber_ = value;
      }
    }

    /// <summary>Field number for the "spectacol" field.</summary>
    public const int SpectacolFieldNumber = 4;
    private global::Ubb.Scs.Mpp.Network.Spectacol spectacol_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ubb.Scs.Mpp.Network.Spectacol Spectacol {
      get { return spectacol_; }
      set {
        spectacol_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Bilet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Bilet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Buyer != other.Buyer) return false;
      if (SeatsNumber != other.SeatsNumber) return false;
      if (!object.Equals(Spectacol, other.Spectacol)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Buyer.Length != 0) hash ^= Buyer.GetHashCode();
      if (SeatsNumber != 0) hash ^= SeatsNumber.GetHashCode();
      if (spectacol_ != null) hash ^= Spectacol.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Buyer.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Buyer);
      }
      if (SeatsNumber != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SeatsNumber);
      }
      if (spectacol_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Spectacol);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Buyer.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Buyer);
      }
      if (SeatsNumber != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SeatsNumber);
      }
      if (spectacol_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Spectacol);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (Buyer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Buyer);
      }
      if (SeatsNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SeatsNumber);
      }
      if (spectacol_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Spectacol);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Bilet other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Buyer.Length != 0) {
        Buyer = other.Buyer;
      }
      if (other.SeatsNumber != 0) {
        SeatsNumber = other.SeatsNumber;
      }
      if (other.spectacol_ != null) {
        if (spectacol_ == null) {
          Spectacol = new global::Ubb.Scs.Mpp.Network.Spectacol();
        }
        Spectacol.MergeFrom(other.Spectacol);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Buyer = input.ReadString();
            break;
          }
          case 24: {
            SeatsNumber = input.ReadInt32();
            break;
          }
          case 34: {
            if (spectacol_ == null) {
              Spectacol = new global::Ubb.Scs.Mpp.Network.Spectacol();
            }
            input.ReadMessage(Spectacol);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Buyer = input.ReadString();
            break;
          }
          case 24: {
            SeatsNumber = input.ReadInt32();
            break;
          }
          case 34: {
            if (spectacol_ == null) {
              Spectacol = new global::Ubb.Scs.Mpp.Network.Spectacol();
            }
            input.ReadMessage(Spectacol);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Request : pb::IMessage<Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ubb.Scs.Mpp.Network.BileteprotobufsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request(Request other) : this() {
      type_ = other.type_;
      angajat_ = other.angajat_ != null ? other.angajat_.Clone() : null;
      bilet_ = other.bilet_ != null ? other.bilet_.Clone() : null;
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Ubb.Scs.Mpp.Network.Request.Types.Type type_ = global::Ubb.Scs.Mpp.Network.Request.Types.Type.BuyTicket;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ubb.Scs.Mpp.Network.Request.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "angajat" field.</summary>
    public const int AngajatFieldNumber = 2;
    private global::Ubb.Scs.Mpp.Network.Angajat angajat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ubb.Scs.Mpp.Network.Angajat Angajat {
      get { return angajat_; }
      set {
        angajat_ = value;
      }
    }

    /// <summary>Field number for the "bilet" field.</summary>
    public const int BiletFieldNumber = 3;
    private global::Ubb.Scs.Mpp.Network.Bilet bilet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ubb.Scs.Mpp.Network.Bilet Bilet {
      get { return bilet_; }
      set {
        bilet_ = value;
      }
    }

    /// <summary>Field number for the "Data" field.</summary>
    public const int DataFieldNumber = 4;
    private string data_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Angajat, other.Angajat)) return false;
      if (!object.Equals(Bilet, other.Bilet)) return false;
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Ubb.Scs.Mpp.Network.Request.Types.Type.BuyTicket) hash ^= Type.GetHashCode();
      if (angajat_ != null) hash ^= Angajat.GetHashCode();
      if (bilet_ != null) hash ^= Bilet.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Ubb.Scs.Mpp.Network.Request.Types.Type.BuyTicket) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (angajat_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Angajat);
      }
      if (bilet_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Bilet);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Ubb.Scs.Mpp.Network.Request.Types.Type.BuyTicket) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (angajat_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Angajat);
      }
      if (bilet_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Bilet);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Ubb.Scs.Mpp.Network.Request.Types.Type.BuyTicket) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (angajat_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Angajat);
      }
      if (bilet_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Bilet);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Ubb.Scs.Mpp.Network.Request.Types.Type.BuyTicket) {
        Type = other.Type;
      }
      if (other.angajat_ != null) {
        if (angajat_ == null) {
          Angajat = new global::Ubb.Scs.Mpp.Network.Angajat();
        }
        Angajat.MergeFrom(other.Angajat);
      }
      if (other.bilet_ != null) {
        if (bilet_ == null) {
          Bilet = new global::Ubb.Scs.Mpp.Network.Bilet();
        }
        Bilet.MergeFrom(other.Bilet);
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Ubb.Scs.Mpp.Network.Request.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            if (angajat_ == null) {
              Angajat = new global::Ubb.Scs.Mpp.Network.Angajat();
            }
            input.ReadMessage(Angajat);
            break;
          }
          case 26: {
            if (bilet_ == null) {
              Bilet = new global::Ubb.Scs.Mpp.Network.Bilet();
            }
            input.ReadMessage(Bilet);
            break;
          }
          case 34: {
            Data = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Ubb.Scs.Mpp.Network.Request.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            if (angajat_ == null) {
              Angajat = new global::Ubb.Scs.Mpp.Network.Angajat();
            }
            input.ReadMessage(Angajat);
            break;
          }
          case 26: {
            if (bilet_ == null) {
              Bilet = new global::Ubb.Scs.Mpp.Network.Bilet();
            }
            input.ReadMessage(Bilet);
            break;
          }
          case 34: {
            Data = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Request message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("BuyTicket")] BuyTicket = 0,
        [pbr::OriginalName("Login")] Login = 1,
        [pbr::OriginalName("Logout")] Logout = 2,
        [pbr::OriginalName("GetShows")] GetShows = 3,
        [pbr::OriginalName("GetFShows")] GetFshows = 4,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TicketResponse : pb::IMessage<TicketResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TicketResponse> _parser = new pb::MessageParser<TicketResponse>(() => new TicketResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TicketResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ubb.Scs.Mpp.Network.BileteprotobufsReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TicketResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TicketResponse(TicketResponse other) : this() {
      type_ = other.type_;
      error_ = other.error_;
      bilet_ = other.bilet_ != null ? other.bilet_.Clone() : null;
      angajat_ = other.angajat_ != null ? other.angajat_.Clone() : null;
      shows_ = other.shows_.Clone();
      spectacol_ = other.spectacol_ != null ? other.spectacol_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TicketResponse Clone() {
      return new TicketResponse(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Ubb.Scs.Mpp.Network.TicketResponse.Types.Type type_ = global::Ubb.Scs.Mpp.Network.TicketResponse.Types.Type.Ok;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ubb.Scs.Mpp.Network.TicketResponse.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bilet" field.</summary>
    public const int BiletFieldNumber = 3;
    private global::Ubb.Scs.Mpp.Network.Bilet bilet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ubb.Scs.Mpp.Network.Bilet Bilet {
      get { return bilet_; }
      set {
        bilet_ = value;
      }
    }

    /// <summary>Field number for the "angajat" field.</summary>
    public const int AngajatFieldNumber = 5;
    private global::Ubb.Scs.Mpp.Network.Angajat angajat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ubb.Scs.Mpp.Network.Angajat Angajat {
      get { return angajat_; }
      set {
        angajat_ = value;
      }
    }

    /// <summary>Field number for the "shows" field.</summary>
    public const int ShowsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Ubb.Scs.Mpp.Network.Spectacol> _repeated_shows_codec
        = pb::FieldCodec.ForMessage(34, global::Ubb.Scs.Mpp.Network.Spectacol.Parser);
    private readonly pbc::RepeatedField<global::Ubb.Scs.Mpp.Network.Spectacol> shows_ = new pbc::RepeatedField<global::Ubb.Scs.Mpp.Network.Spectacol>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ubb.Scs.Mpp.Network.Spectacol> Shows {
      get { return shows_; }
    }

    /// <summary>Field number for the "spectacol" field.</summary>
    public const int SpectacolFieldNumber = 6;
    private global::Ubb.Scs.Mpp.Network.Spectacol spectacol_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ubb.Scs.Mpp.Network.Spectacol Spectacol {
      get { return spectacol_; }
      set {
        spectacol_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TicketResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TicketResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Error != other.Error) return false;
      if (!object.Equals(Bilet, other.Bilet)) return false;
      if (!object.Equals(Angajat, other.Angajat)) return false;
      if(!shows_.Equals(other.shows_)) return false;
      if (!object.Equals(Spectacol, other.Spectacol)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Ubb.Scs.Mpp.Network.TicketResponse.Types.Type.Ok) hash ^= Type.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (bilet_ != null) hash ^= Bilet.GetHashCode();
      if (angajat_ != null) hash ^= Angajat.GetHashCode();
      hash ^= shows_.GetHashCode();
      if (spectacol_ != null) hash ^= Spectacol.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Ubb.Scs.Mpp.Network.TicketResponse.Types.Type.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (bilet_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Bilet);
      }
      shows_.WriteTo(output, _repeated_shows_codec);
      if (angajat_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Angajat);
      }
      if (spectacol_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Spectacol);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Ubb.Scs.Mpp.Network.TicketResponse.Types.Type.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (bilet_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Bilet);
      }
      shows_.WriteTo(ref output, _repeated_shows_codec);
      if (angajat_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Angajat);
      }
      if (spectacol_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Spectacol);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Ubb.Scs.Mpp.Network.TicketResponse.Types.Type.Ok) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (bilet_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Bilet);
      }
      if (angajat_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Angajat);
      }
      size += shows_.CalculateSize(_repeated_shows_codec);
      if (spectacol_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Spectacol);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TicketResponse other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Ubb.Scs.Mpp.Network.TicketResponse.Types.Type.Ok) {
        Type = other.Type;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      if (other.bilet_ != null) {
        if (bilet_ == null) {
          Bilet = new global::Ubb.Scs.Mpp.Network.Bilet();
        }
        Bilet.MergeFrom(other.Bilet);
      }
      if (other.angajat_ != null) {
        if (angajat_ == null) {
          Angajat = new global::Ubb.Scs.Mpp.Network.Angajat();
        }
        Angajat.MergeFrom(other.Angajat);
      }
      shows_.Add(other.shows_);
      if (other.spectacol_ != null) {
        if (spectacol_ == null) {
          Spectacol = new global::Ubb.Scs.Mpp.Network.Spectacol();
        }
        Spectacol.MergeFrom(other.Spectacol);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Ubb.Scs.Mpp.Network.TicketResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            if (bilet_ == null) {
              Bilet = new global::Ubb.Scs.Mpp.Network.Bilet();
            }
            input.ReadMessage(Bilet);
            break;
          }
          case 34: {
            shows_.AddEntriesFrom(input, _repeated_shows_codec);
            break;
          }
          case 42: {
            if (angajat_ == null) {
              Angajat = new global::Ubb.Scs.Mpp.Network.Angajat();
            }
            input.ReadMessage(Angajat);
            break;
          }
          case 50: {
            if (spectacol_ == null) {
              Spectacol = new global::Ubb.Scs.Mpp.Network.Spectacol();
            }
            input.ReadMessage(Spectacol);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Ubb.Scs.Mpp.Network.TicketResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            if (bilet_ == null) {
              Bilet = new global::Ubb.Scs.Mpp.Network.Bilet();
            }
            input.ReadMessage(Bilet);
            break;
          }
          case 34: {
            shows_.AddEntriesFrom(ref input, _repeated_shows_codec);
            break;
          }
          case 42: {
            if (angajat_ == null) {
              Angajat = new global::Ubb.Scs.Mpp.Network.Angajat();
            }
            input.ReadMessage(Angajat);
            break;
          }
          case 50: {
            if (spectacol_ == null) {
              Spectacol = new global::Ubb.Scs.Mpp.Network.Spectacol();
            }
            input.ReadMessage(Spectacol);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the TicketResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Ok")] Ok = 0,
        [pbr::OriginalName("NewTicket")] NewTicket = 1,
        [pbr::OriginalName("Error")] Error = 2,
        [pbr::OriginalName("ShowList")] ShowList = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
