plugins {
    id 'java'
    id 'org.openjfx.javafxplugin' version '0.0.13'
    id 'application'
}

group = 'ubb.scs.mpp'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

javafx {
    version = '17.0.2'
    modules = ['javafx.controls', 'javafx.fxml']
}

application{
    mainClass='ubb.scs.mpp.Main'
}
dependencies {

    implementation project(':Domain')
    implementation project(':Repository')
    implementation project(':Service')
    implementation project(':Network')

    implementation('org.controlsfx:controlsfx:11.1.1')
    implementation('com.dlsc.formsfx:formsfx-core:11.5.0') {
        exclude(group: 'org.openjfx')
    }
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    implementation 'org.openjfx:javafx-controls:21'
    implementation 'org.openjfx:javafx-fxml:21'

}

test {
    useJUnitPlatform()
}

jar {
    duplicatesStrategy (DuplicatesStrategy.EXCLUDE)
    manifest {
        attributes('Main-Class':'ubb.scs.mpp.Main')
    }
    from {
        configurations.runtimeClasspath.collect{it.isDirectory()?it:zipTree(it)}
    }
}