plugins {
    id 'org.springframework.boot' version '3.2.0'
    id 'io.spring.dependency-management' version '1.1.5'
    id 'java'
}

group = 'ubb.scs.mpp'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project (':Domain')
    implementation project (':Repository')
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-annotations', version: '2.13.1'

    testImplementation('com.jayway.jsonpath:json-path')
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation('org.springframework.boot:spring-boot-starter-test')
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.3'
    // https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-api
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    // https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-impl
    implementation 'io.jsonwebtoken:jjwt-impl:0.12.6'

    // https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-jackson
    implementation 'io.jsonwebtoken:jjwt-jackson:0.12.6'
    implementation 'org.springframework.security:spring-security-crypto:6.4.4'

}

test {
    useJUnitPlatform()
}