plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'ubb.scs.mpp'
version = '1.0-SNAPSHOT'

javafx {
    version = "21"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}
repositories {
    mavenCentral()
}
application{
    mainClass='ubb.scs.mpp.Main'
}
dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'org.xerial:sqlite-jdbc:3.49.1.0'
    implementation 'org.apache.logging.log4j:log4j-api:2.20.0'
    implementation 'org.apache.logging.log4j:log4j-core:2.20.0'
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version:'5.8.2'
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-engine',
            version:'5.8.2'
    implementation 'org.openjfx:javafx-controls:21'
    implementation 'org.openjfx:javafx-fxml:21'
    // https://mvnrepository.com/artifact/org.springframework/spring-context
    implementation("org.springframework:spring-context:7.0.0-M3")
    // https://mvnrepository.com/artifact/org.springframework.security/spring-security-crypto
    implementation("org.springframework.security:spring-security-crypto:6.4.4")
}

test {
    useJUnitPlatform()
}